# Generated by Django 3.1.2 on 2020-10-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_phone', models.CharField(max_length=100)),
                ('church_email', models.CharField(max_length=100)),
                ('church_location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CHurch Contact',
                'verbose_name_plural': 'Church Contancts',
                'ordering': ['-id'],
            },
        ),
    ]
