# Generated by Django 3.1.2 on 2020-10-31 01:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='sermon',
            field=embed_video.fields.EmbedVideoField(help_text='Add the link of the sermon from youtube or facebook'),
        ),
    ]
