# Generated by Django 3.1.2 on 2020-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.CharField(default=0.0, help_text='If free write 0.00 otherwise input the amount', max_length=100),
        ),
    ]
