# Generated by Django 3.1.2 on 2020-10-30 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chairperson', models.CharField(max_length=100)),
                ('vice_chairperson', models.CharField(max_length=100)),
                ('treasurer', models.CharField(max_length=100)),
                ('secretary', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'ordering': ['date_posted'],
            },
        ),
    ]
