# Generated by Django 3.1.2 on 2020-10-27 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['date_posted'], 'verbose_name': 'Leaders', 'verbose_name_plural': 'DC Kenol Team'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission', 'verbose_name_plural': 'Mission'},
        ),
        migrations.RemoveField(
            model_name='leader',
            name='photo',
        ),
        migrations.AddField(
            model_name='about',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(default='about', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Leaders/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_leader',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_pastor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
