# Generated by Django 3.1.2 on 2020-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201027_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belief',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.AddField(
            model_name='about',
            name='beliefs',
            field=models.TextField(default='our beliefs'),
        ),
        migrations.AddField(
            model_name='about',
            name='benefits',
            field=models.TextField(default='the benefits'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(default='our mission'),
        ),
    ]
