# Generated by Django 3.1.2 on 2020-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(blank=True, default='who-are-we', max_length=200, null=True, unique=True),
        ),
    ]
