# Generated by Django 3.1.2 on 2020-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slug',
            field=models.SlugField(default='who-are-we', max_length=200, null=True, unique=True),
        ),
    ]
