# Generated by Django 3.1.2 on 2020-11-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20201106_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Photo Category', 'verbose_name_plural': 'Photo Categories'},
        ),
    ]
